### ISSUE TITLE
[FEATURE] Include group variables for blacklisted variables

### ISSUE THREAD

**Issue by L-McKendrick** [TMZulu/ZHC#12]
My community mission makers primarily use group variables. However, the Blacklisted Variables CBA setting only works with individual object variables.

If the Blacklisted Variables worked with group variables as well, it would provide an easier way to blacklist groups of AI. A separate setting could work as well.

**Comment by TMZulu** [comment]
Sorry for the long delay in response. Could look into it. I haven't really messed with group classnames but as long as they are accessible, it should be possible to add them to blacklisting functionality.

**Comment by TMZulu** [comment]
Unfortunately, Arma does not have any native functions/commands in order determine the classname of a group after spawning. Once it is spawned, the group has no knowledge of what cfgGroup it was a part of. It is just a collection of units at that point. 
Additionally, the relevant event handlers do not provide the class names either. As such, it is not possible to implement this request outside of creating a module to spawn units instead of the zeus menu, which defeats the purpose of it. 

You can try spawning and naming the groups in the editor and then using them during the mission if they require blacklisting. They would all need to be pre-spawned though.
